---
- hosts: "localhost"
  gather_facts: no
  vars_files:
  - vars.yml
  - iterate_hosts.yml

  tasks:
  - name: "login"
    check_point_mgmt:
      command: login
      parameters:
        username: "{{mgmt_user}}"
        password: "{{mgmt_password}}"
        management: "{{mgmt_server}}"
      fingerprint: "{{mgmt_fingerprint}}"
    register: login_response
    
  - name: "Adding hosts to mgmt database"
    check_point_mgmt:
      session-data: "{{login_response}}"
      command: add-host
      parameters:
         name: "{{item.name}}"
         ip-address: "{{item.ip_address}}"
         groups: "{{item.group}}"
    with_items: "{{cp_hosts}}"

  - name: "publish"
    check_point_mgmt:
      command: publish
      session-data: "{{login_response}}"

  - name: "logout"
    check_point_mgmt:
      command: logout 
      session-data: "{{login_response}}"
